

services:
  mysql:
    image: mysql:8.1.0
    container_name: minpdb
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: reactspring
      MYSQL_USER: developer
      MYSQL_PASSWORD: dev1234
    ports:
      - "3302:3306"
    networks:
      - minp-network

  minp-back:
    image: minp-back
    container_name : minp-back
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
    ports:
      - "3301:3300"
    networks:
    - minp-network

networks:
  minp-network: